CUDA_VISIBLE_DEVICES=0 llamafactory-cli train \
    --stage sft \
    --do_train \
    --model_name_or_path /home/ubuntu/lsh/project/Socratic/Model/Qwen2.5-Math-7B-Instruct \
    --dataset socratic_dialogue \
    --dataset_dir /home/ubuntu/LLaMA-Factory/data \
    --template qwen \
    --finetuning_type lora \
    --output_dir /home/ubuntu/lsh/project/SocraticLM/saves \
    --overwrite_cache \
    --overwrite_output_dir \
    --cutoff_len 1024 \
    --preprocessing_num_workers 16 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 50 \
    --warmup_steps 20 \
    --save_steps 100 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --learning_rate 5e-5 \
    --num_train_epochs 5.0 \
    --max_samples  100000 \
    --val_size 0.1 \
    --plot_loss \
    --fp16